// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iveylzwapmtaawyurxal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZXlsendhcG10YWF3eXVyeGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNDM5OTUsImV4cCI6MjA2ODcxOTk5NX0.276NJ5pBzD4uy8KS1dA34M-ZSUVvco1P-DXuayCgnbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});